name: Deploy to GitHub Pages - test

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Add ng cli
        run: npm install -g @angular/cli

      - name: Replace api_url in environment.ts
        run: sed -i "s|API_URL|${{ secrets.API_URL }}|g" src/environments/environment.ts

      - name: Replace api_key in environment.prod.ts
        run: sed -i "s|API_KEY|${{ secrets.API_KEY }}|g" src/environments/environment.ts

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: ng deploy --base-href=/gh-strani-test/ --no-silent --name="Anej" --email=team@angular.schule
